# Generated by Django 5.2.17 on 2026-09-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_coupon_first_order_only_coupon_max_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('missing_item', 'Missing Item'), ('wrong_item', 'Wrong Item'), ('food_quality', 'Food Quality'), ('delivery', 'Delivery'), ('payment', 'Payment'), ('refund', 'Refund'), ('account', 'Account'), ('privacy', 'Privacy'), ('other', 'Other')], max_length=30),
        ),
    ]
