# Generated by Django 5.2.17 on 2026-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notification_event_deduplication'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_menu_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='configuration_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='add_ons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'menu_item', 'configuration_key'), name='unique_cart_item_configuration'),
        ),
    ]
