# Generated by Django 5.2.17 on 2026-09-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_taste_profiles_and_restaurant_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='option_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
