# Generated by Django 5.2.17 on 2026-09-22 05:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta


def initialize_policy_and_deadlines(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model('api', 'DeliveryPolicy').objects.using(alias).get_or_create(pk=1)
    # Existing unpaid orders receive a full grace window from migration time.
    apps.get_model('api', 'Order').objects.using(alias).filter(status='awaiting_payment', payment_expires_at__isnull=True).update(payment_expires_at=timezone.now()+timedelta(minutes=15))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delivery_location_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_quote',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(100)])),
                ('max_delivery_km', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10')), django.core.validators.MaxValueValidator(100)])),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('included_km', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('free_delivery_above', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['city', 'id'],
                'constraints': [models.UniqueConstraint(fields=('city', 'name'), name='unique_delivery_zone_name')],
            },
        ),
        migrations.RunPython(initialize_policy_and_deadlines, migrations.RunPython.noop),
    ]
