# Generated by Django 5.2.17 on 2026-09-22 05:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delivery_zones_and_payment_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='affected_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='feedback_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='feedback_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('reviewing', 'Under review'), ('approved', 'Approved, awaiting payment processing'), ('processing', 'Processing'), ('processed', 'Refund processed'), ('rejected', 'Not approved'), ('failed', 'Processing failed')], db_index=True, default='requested', max_length=12)),
                ('decision_note', models.CharField(blank=True, max_length=1000)),
                ('provider_refund_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='api.order')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_request', to='api.supportticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
