# Generated by Django 5.2.17 on 2026-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_refund_reviews_and_support_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutoff', models.CharField(choices=[('acceptance', 'Before restaurant acceptance'), ('preparation', 'Before cooking starts')], default='acceptance', max_length=20)),
                ('allow_prepaid_refunds', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='automatic_cancellation',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
