# Generated by Django 5.2.17 on 2026-09-22 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cancellation_policy_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_orders', to='api.supportticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
