# Generated by Django 5.2.17 on 2026-09-22 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_order_fulfillment_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='staff_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='client_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='reply_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_reply', to='api.ticketmessage'),
        ),
        migrations.AddConstraint(
            model_name='ticketmessage',
            constraint=models.UniqueConstraint(fields=('ticket', 'author', 'client_id'), name='unique_ticket_client_message'),
        ),
    ]
