# Generated by Django 5.2.17 on 2026-09-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_persisted_support_assistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1000)),
                ('client_id', models.UUIDField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_delivery_messages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_messages', to='api.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order', 'partner', 'id'], name='delivery_message_thread_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'author', 'client_id'), name='delivery_message_retry_unique')],
            },
        ),
    ]
