# Generated by Django 5.2.17 on 2026-09-23 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_coupon_benefits_campaigns'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('points_per_100', models.PositiveIntegerField(default=0)),
                ('point_value', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('redemption_percent', models.PositiveIntegerField(default=0)),
                ('cashback_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cashback_cap', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('referral_credit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('referral_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('tiers', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='reward_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='reward_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RewardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.BigIntegerField(default=0)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qualifying_points', models.BigIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('referral_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('referral_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_qualification', to='api.order')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_reward_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reward_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RewardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('redeem', 'Used at checkout'), ('restore', 'Returned rewards'), ('earn', 'Order rewards'), ('referral', 'Referral reward')], max_length=20)),
                ('points', models.BigIntegerField(default=0)),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qualifying_points', models.BigIntegerField(default=0)),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='api.rewardaccount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_entries', to='api.order')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['account', 'order', 'kind'], name='reward_reconcile_idx')],
            },
        ),
    ]
