# Generated by Django 5.2.17 on 2026-09-23 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_city_availability_delivery_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('settlement_recording_enabled', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='commission_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='merchant_account', to='api.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('client_id', models.UUIDField(unique=True)),
                ('paid_at', models.DateTimeField()),
                ('note', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_note', models.CharField(blank=True, max_length=500)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='api.merchantaccount')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MerchantEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accrual', 'Order accrual / refund adjustment'), ('settlement', 'External payment recorded'), ('correction', 'Settlement record corrected')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('merchant_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('platform_promotion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('delivery_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tip_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('event_key', models.CharField(max_length=120, unique=True)),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='api.merchantaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchant_entries', to='api.order')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.merchantsettlement')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='merchantsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='merchant_settlement_positive'),
        ),
        migrations.AddIndex(
            model_name='merchantentry',
            index=models.Index(fields=['account', 'order', 'kind'], name='merchant_reconcile_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchantentry',
            constraint=models.UniqueConstraint(fields=('settlement', 'kind'), name='merchant_settlement_entry_once'),
        ),
    ]
