import {
  BarChart3,
  Bike,
  CreditCard,
  LayoutDashboard,
  ListChecks,
  MapPin,
  MessageSquare,
  Settings,
  ShoppingBag,
  Store,
  Tag,
  Users,
  Utensils,
} from "lucide-react";

export const workspaceMenus = {
  restaurant: [
    ["dashboard", "Overview", LayoutDashboard],
    ["orders", "Live orders", ShoppingBag],
    ["menu", "Your menu", Utensils],
    ["profile", "Restaurant profile", Store],
    ["offers", "Offers", Tag],
    ["earnings", "Earnings & payments", CreditCard],
    ["analytics", "Analytics", BarChart3],
  ],
  delivery: [
    ["dashboard", "Overview", LayoutDashboard],
    ["orders", "Delivery requests", ShoppingBag],
    ["navigation", "Active delivery", MapPin],
    ["earnings", "Delivery history", CreditCard],
    ["profile", "My profile", Bike],
  ],
  admin: [
    ["dashboard", "Overview", LayoutDashboard],
    ["orders", "Orders", ShoppingBag],
    ["restaurants", "Restaurants", Store],
    ["delivery-partners", "Delivery partners", Bike],
    ["partner-accounts", "Partner account access", Users],
    ["users", "People", Users],
    ["payments", "Payments & earnings", CreditCard],
    ["delivery-zones", "Delivery areas", MapPin],
    ["order-policy", "Order policy", ListChecks],
    ["offers", "Offers & coupons", Tag],
    ["catalog", "Food categories", Utensils],
    ["reports", "Analytics", BarChart3],
    ["reviews", "Review moderation", MessageSquare],
    ["activity", "Activity log", ListChecks],
    ["profile", "My profile", Settings],
    ["access", "Team access", Users],
  ],
};
